export interface Provider {
  slug: string;
  name: string;
  category: string;
  description: string;
  location: string;
  suburb: string;
  rating: number;
  reviewCount: number;
  verified: boolean;
  services: string[];
  phone: string;
  email: string;
  image: string;
  plan: "free" | "starter" | "pro" | "premium";
}

export const providers: Provider[] = [
  {
    slug: "sunshine-support-services",
    name: "Sunshine Support Services",
    category: "Daily Living",
    description: "Person-centred daily living support across Newcastle. Specialising in community access, personal care, and independent living skills.",
    location: "Newcastle CBD",
    suburb: "Newcastle CBD",
    rating: 4.9,
    reviewCount: 127,
    verified: true,
    services: ["Personal Care", "Community Access", "Meal Preparation", "Transport"],
    phone: "02 4925 1100",
    email: "hello@sunshinesupport.com.au",
    image: "/providers/sunshine.jpg",
    plan: "premium",
  },
  {
    slug: "hunter-valley-therapy",
    name: "Hunter Valley Therapy",
    category: "Allied Health",
    description: "Multidisciplinary therapy practice offering OT, speech, and psychology services throughout the Hunter Valley.",
    location: "Maitland",
    suburb: "Maitland",
    rating: 4.8,
    reviewCount: 94,
    verified: true,
    services: ["Occupational Therapy", "Speech Pathology", "Psychology", "Behaviour Support"],
    phone: "02 4933 2200",
    email: "info@huntervalleytherapy.com.au",
    image: "/providers/hunter-therapy.jpg",
    plan: "pro",
  },
  {
    slug: "physioplus-newcastle",
    name: "PhysioPlus Newcastle",
    category: "Allied Health",
    description: "Expert physiotherapy and exercise physiology for NDIS participants. Hydrotherapy pool on-site.",
    location: "Adamstown",
    suburb: "Adamstown",
    rating: 4.7,
    reviewCount: 83,
    verified: true,
    services: ["Physiotherapy", "Exercise Physiology", "Hydrotherapy", "Group Programs"],
    phone: "02 4952 3300",
    email: "book@physioplusnewcastle.com.au",
    image: "/providers/physioplus.jpg",
    plan: "pro",
  },
  {
    slug: "little-stars-early-intervention",
    name: "Little Stars Early Intervention",
    category: "Early Intervention",
    description: "Play-based early childhood intervention for children 0-6 years. NDIS early childhood partner.",
    location: "Charlestown",
    suburb: "Charlestown",
    rating: 4.9,
    reviewCount: 156,
    verified: true,
    services: ["Early Intervention", "Play Therapy", "Family Support", "Developmental Assessment"],
    phone: "02 4943 4400",
    email: "enquiries@littlestars.com.au",
    image: "/providers/little-stars.jpg",
    plan: "premium",
  },
  {
    slug: "carefirst-community",
    name: "CareFirst Community",
    category: "Support Coordination",
    description: "Specialist support coordination helping participants navigate their NDIS plans and connect with the right services.",
    location: "Cessnock",
    suburb: "Cessnock",
    rating: 4.6,
    reviewCount: 61,
    verified: true,
    services: ["Support Coordination", "Plan Management", "Capacity Building", "Advocacy"],
    phone: "02 4990 5500",
    email: "connect@carefirst.com.au",
    image: "/providers/carefirst.jpg",
    plan: "starter",
  },
  {
    slug: "lakeside-allied-health",
    name: "Lakeside Allied Health",
    category: "Allied Health",
    description: "Comprehensive allied health services on the shores of Lake Macquarie. OT, speech, and dietetics.",
    location: "Belmont",
    suburb: "Belmont",
    rating: 4.8,
    reviewCount: 72,
    verified: true,
    services: ["Occupational Therapy", "Speech Pathology", "Dietetics", "Art Therapy"],
    phone: "02 4945 6600",
    email: "hello@lakesidehealth.com.au",
    image: "/providers/lakeside.jpg",
    plan: "pro",
  },
  {
    slug: "newcastle-disability-services",
    name: "Newcastle Disability Services",
    category: "Daily Living",
    description: "Full-service disability support provider. SIL, respite, and community participation programs.",
    location: "Hamilton",
    suburb: "Hamilton",
    rating: 4.5,
    reviewCount: 108,
    verified: true,
    services: ["SIL", "Respite", "Community Participation", "Skill Development"],
    phone: "02 4961 7700",
    email: "info@nds.org.au",
    image: "/providers/nds.jpg",
    plan: "pro",
  },
  {
    slug: "hunter-support-co",
    name: "Hunter Support Co",
    category: "Plan Management",
    description: "Transparent plan management with real-time budget tracking. No hidden fees, no lock-in contracts.",
    location: "Newcastle West",
    suburb: "Newcastle West",
    rating: 4.7,
    reviewCount: 89,
    verified: true,
    services: ["Plan Management", "Budget Tracking", "Invoice Processing", "Reporting"],
    phone: "02 4926 8800",
    email: "plans@huntersupport.co",
    image: "/providers/hunter-support.jpg",
    plan: "starter",
  },
  {
    slug: "valley-view-care",
    name: "Valley View Care",
    category: "Accommodation",
    description: "Modern supported independent living homes across the Hunter Valley. 24/7 on-site support available.",
    location: "Kurri Kurri",
    suburb: "Kurri Kurri",
    rating: 4.6,
    reviewCount: 45,
    verified: false,
    services: ["SIL", "SDA", "Respite", "Short-Term Accommodation"],
    phone: "02 4937 9900",
    email: "living@valleyviewcare.com.au",
    image: "/providers/valley-view.jpg",
    plan: "free",
  },
  {
    slug: "coastal-wellness-group",
    name: "Coastal Wellness Group",
    category: "Mental Health",
    description: "Recovery-focused mental health support. Psychosocial recovery coaching and peer support programs.",
    location: "Merewether",
    suburb: "Merewether",
    rating: 4.8,
    reviewCount: 67,
    verified: true,
    services: ["Recovery Coaching", "Peer Support", "Group Programs", "Crisis Support"],
    phone: "02 4963 1100",
    email: "support@coastalwellness.com.au",
    image: "/providers/coastal.jpg",
    plan: "starter",
  },
  {
    slug: "hunter-transport-solutions",
    name: "Hunter Transport Solutions",
    category: "Transport",
    description: "Reliable, accessible transport for NDIS participants across the Hunter Region. Wheelchair-accessible vehicles and trained drivers.",
    location: "Wallsend",
    suburb: "Wallsend",
    rating: 4.5,
    reviewCount: 38,
    verified: false,
    services: ["Transport Assistance", "Community Transport", "Airport Transfers", "Medical Appointments"],
    phone: "02 4955 3344",
    email: "bookings@huntertransport.com.au",
    image: "/providers/hunter-transport.jpg",
    plan: "free",
  },
  {
    slug: "maitland-sil-homes",
    name: "Maitland SIL Homes",
    category: "Accommodation",
    description: "Purpose-built SDA and SIL homes in Maitland and surrounding areas. Robust and fully accessible designs for high physical support needs.",
    location: "Maitland",
    suburb: "Maitland",
    rating: 4.4,
    reviewCount: 29,
    verified: false,
    services: ["SDA", "SIL", "24/7 Support", "Household Tasks"],
    phone: "02 4933 7788",
    email: "homes@maitlandsil.com.au",
    image: "/providers/maitland-sil.jpg",
    plan: "free",
  },
];

export const categories = [
  "All",
  "Allied Health",
  "Daily Living",
  "Support Coordination",
  "Plan Management",
  "Early Intervention",
  "Mental Health",
  "Accommodation",
  "Transport",
];

export const locations = [
  "All Locations",
  "Newcastle CBD",
  "Maitland",
  "Charlestown",
  "Cessnock",
  "Belmont",
  "Hamilton",
  "Newcastle West",
  "Kurri Kurri",
  "Merewether",
  "Adamstown",
  "Wallsend",
  "Lake Macquarie",
];