$svc = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmaGFwbm5seGZoeHNxcHFjdWplIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjA0NDYyOCwiZXhwIjoyMDg3NjIwNjI4fQ.iBMN0RjFjP_woNhZPtgwsaHyAWscGF2Jc3BVOkG78cE"
$url = "https://zfhapnnlxfhxsqpqcuje.supabase.co/rest/v1/providers"

$providers = @'
[
  {
    "name": "Samaritans",
    "email": "info@samaritans.org.au",
    "tier": "professional",
    "verified": true,
    "categories": ["daily-living","community-access","supported-living"],
    "suburb": "Newcastle",
    "state": "NSW",
    "postcode": "2300",
    "phone": "02 4960 7100",
    "website": "https://www.samaritans.org.au",
    "description": "Samaritans is one of the Hunter regions largest NDIS providers, offering flexible disability support across Newcastle, Lake Macquarie, Maitland, Upper Hunter, Central Coast and Mid North Coast. Services include daily living support, community access, supported independent living, and social programs.",
    "short_description": "Trusted Hunter Region provider — daily living, community access & supported living across Newcastle and beyond.",
    "rating": 4.5,
    "review_count": 12,
    "response_rate": 92,
    "response_time": "Within 24 hours",
    "wait_time": "1-2 weeks",
    "plan_types": ["NDIA Managed","Plan Managed","Self Managed"],
    "availability": {"mon":"8am-5pm","tue":"8am-5pm","wed":"8am-5pm","thu":"8am-5pm","fri":"8am-5pm","sat":"Closed","sun":"Closed"},
    "service_areas": ["Newcastle","Lake Macquarie","Maitland","Upper Hunter","Central Coast"],
    "founded": "1984",
    "team_size": "200+",
    "languages": ["English","Arabic","Mandarin"],
    "features": ["NDIS Registered","24/7 Support Available","Transport Available"],
    "slug": "samaritans",
    "services": ["daily-living","community-access","supported-living"],
    "location": "Newcastle",
    "category": "Daily Living",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#1e40af"
  },
  {
    "name": "Songbird Disability Services",
    "email": "info@songbird.com.au",
    "tier": "professional",
    "verified": true,
    "categories": ["daily-living","community-access","therapeutic"],
    "suburb": "Newcastle",
    "state": "NSW",
    "postcode": "2300",
    "phone": "02 4023 3900",
    "website": "https://www.songbird.com.au",
    "description": "Songbird is an NDIS registered provider offering a range of disability support services across Newcastle, Lake Macquarie, Maitland and the Hunter Valley. Person-centred approach empowering individuals with a disability to lead their best life.",
    "short_description": "Person-centred disability support across Newcastle, Lake Macquarie and the Hunter Valley.",
    "rating": 4.7,
    "review_count": 18,
    "response_rate": 95,
    "response_time": "Within 24 hours",
    "wait_time": "1 week",
    "plan_types": ["NDIA Managed","Plan Managed","Self Managed"],
    "availability": {"mon":"8am-6pm","tue":"8am-6pm","wed":"8am-6pm","thu":"8am-6pm","fri":"8am-6pm","sat":"By appointment","sun":"Closed"},
    "service_areas": ["Newcastle","Lake Macquarie","Maitland","Hunter Valley"],
    "founded": "2016",
    "team_size": "50-100",
    "languages": ["English"],
    "features": ["NDIS Registered","Person-Centred","Group Programs"],
    "slug": "songbird-disability-services",
    "services": ["daily-living","community-access","therapeutic"],
    "location": "Newcastle",
    "category": "Daily Living",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#059669"
  },
  {
    "name": "Hunter Primary Care",
    "email": "info@hunterprimarycare.com.au",
    "tier": "professional",
    "verified": true,
    "categories": ["therapeutic","mental-health","coordination"],
    "suburb": "New Lambton",
    "state": "NSW",
    "postcode": "2305",
    "phone": "02 4925 2259",
    "website": "https://hunterprimarycare.com.au",
    "description": "As a registered NDIS provider since the scheme was first piloted in the Hunter region in 2013, Hunter Primary Care has deep expertise in NDIS plan management, coordination and therapeutic supports.",
    "short_description": "NDIS pioneer since 2013 — therapeutic supports, mental health and plan coordination in the Hunter.",
    "rating": 4.4,
    "review_count": 9,
    "response_rate": 88,
    "response_time": "1-2 business days",
    "wait_time": "2-3 weeks",
    "plan_types": ["NDIA Managed","Plan Managed"],
    "availability": {"mon":"8:30am-5pm","tue":"8:30am-5pm","wed":"8:30am-5pm","thu":"8:30am-5pm","fri":"8:30am-5pm","sat":"Closed","sun":"Closed"},
    "service_areas": ["Newcastle","Lake Macquarie","Hunter Valley","Maitland"],
    "founded": "2013",
    "team_size": "100+",
    "languages": ["English"],
    "features": ["NDIS Registered","Allied Health","Mental Health Specialists"],
    "slug": "hunter-primary-care",
    "services": ["therapeutic","mental-health","coordination"],
    "location": "New Lambton",
    "category": "Therapeutic",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#7c3aed"
  },
  {
    "name": "EnableU",
    "email": "newcastle@enableu.com.au",
    "tier": "professional",
    "verified": true,
    "categories": ["daily-living","community-access","plan-management"],
    "suburb": "Newcastle",
    "state": "NSW",
    "postcode": "2300",
    "phone": "1300 002 001",
    "website": "https://enableu.com.au",
    "description": "EnableU Newcastle covers local government areas of Newcastle City Council and Lake Macquarie City in the Hunter region. Providing daily living, community access, and plan management services.",
    "short_description": "Local NDIS provider covering Newcastle and Lake Macquarie — daily living, community access and plan management.",
    "rating": 4.3,
    "review_count": 7,
    "response_rate": 90,
    "response_time": "Within 24 hours",
    "wait_time": "1-2 weeks",
    "plan_types": ["NDIA Managed","Plan Managed","Self Managed"],
    "availability": {"mon":"8am-5pm","tue":"8am-5pm","wed":"8am-5pm","thu":"8am-5pm","fri":"8am-5pm","sat":"Closed","sun":"Closed"},
    "service_areas": ["Newcastle","Lake Macquarie"],
    "founded": "2018",
    "team_size": "50-100",
    "languages": ["English","Hindi","Punjabi"],
    "features": ["NDIS Registered","Plan Management","Support Coordination"],
    "slug": "enableu-newcastle",
    "services": ["daily-living","community-access","plan-management"],
    "location": "Newcastle",
    "category": "Daily Living",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#dc2626"
  },
  {
    "name": "Hunter Care Group",
    "email": "info@huntercaregroup.org",
    "tier": "professional",
    "verified": true,
    "categories": ["mental-health","psychosocial","recovery-coaching"],
    "suburb": "Newcastle",
    "state": "NSW",
    "postcode": "2300",
    "phone": "02 4040 7700",
    "website": "https://huntercaregroup.org",
    "description": "Leveraging in-depth knowledge of mental health conditions and services, Hunter Care Groups experienced psychosocial recovery coaches help NDIS participants overcome barriers to participation, boost resilience and thrive.",
    "short_description": "Specialist mental health and psychosocial recovery coaching for NDIS participants in Newcastle.",
    "rating": 4.6,
    "review_count": 14,
    "response_rate": 94,
    "response_time": "Within 24 hours",
    "wait_time": "1-2 weeks",
    "plan_types": ["NDIA Managed","Plan Managed","Self Managed"],
    "availability": {"mon":"8am-5pm","tue":"8am-5pm","wed":"8am-5pm","thu":"8am-5pm","fri":"8am-5pm","sat":"Closed","sun":"Closed"},
    "service_areas": ["Newcastle","Hunter Region"],
    "founded": "2015",
    "team_size": "50+",
    "languages": ["English"],
    "features": ["NDIS Registered","Mental Health Focus","Recovery Coaching"],
    "slug": "hunter-care-group",
    "services": ["mental-health","psychosocial","recovery-coaching"],
    "location": "Newcastle",
    "category": "Mental Health",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#0891b2"
  },
  {
    "name": "Solid Holistic Care",
    "email": "info@solidholisticcare.com.au",
    "tier": "professional",
    "verified": true,
    "categories": ["daily-living","community-access","supported-living"],
    "suburb": "Newcastle",
    "state": "NSW",
    "postcode": "2300",
    "phone": "02 4032 8000",
    "website": "https://www.solidholisticcare.com.au",
    "description": "Solid Holistic Care is a registered NDIS provider in Newcastle delivering disability support across the Hunter region including Lake Macquarie and Maitland. Holistic approach to daily living, community participation and supported independent living.",
    "short_description": "Holistic disability support across Newcastle, Lake Macquarie and Maitland.",
    "rating": 4.2,
    "review_count": 6,
    "response_rate": 85,
    "response_time": "1-2 business days",
    "wait_time": "1-2 weeks",
    "plan_types": ["NDIA Managed","Plan Managed","Self Managed"],
    "availability": {"mon":"8am-5pm","tue":"8am-5pm","wed":"8am-5pm","thu":"8am-5pm","fri":"8am-5pm","sat":"Closed","sun":"Closed"},
    "service_areas": ["Newcastle","Lake Macquarie","Maitland"],
    "founded": "2019",
    "team_size": "20-50",
    "languages": ["English","African Languages"],
    "features": ["NDIS Registered","Holistic Approach","Cultural Sensitivity"],
    "slug": "solid-holistic-care",
    "services": ["daily-living","community-access","supported-living"],
    "location": "Newcastle",
    "category": "Daily Living",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#ea580c"
  },
  {
    "name": "VHCC - Virtue Health & Community Care",
    "email": "info@vhcc.au",
    "tier": "professional",
    "verified": true,
    "categories": ["daily-living","personal-care","supported-living"],
    "suburb": "Newcastle",
    "state": "NSW",
    "postcode": "2300",
    "phone": "1300 842 228",
    "website": "https://vhcc.au",
    "description": "VHCC offers a wide range of NDIS services including personal care, supported accommodation, NDIS plan coordination, therapy services and assistance with daily living tasks in Newcastle.",
    "short_description": "Registered NDIS provider — personal care, supported accommodation and plan coordination in Newcastle.",
    "rating": 4.1,
    "review_count": 5,
    "response_rate": 82,
    "response_time": "1-2 business days",
    "wait_time": "2 weeks",
    "plan_types": ["NDIA Managed","Plan Managed","Self Managed"],
    "availability": {"mon":"8am-5pm","tue":"8am-5pm","wed":"8am-5pm","thu":"8am-5pm","fri":"8am-5pm","sat":"By appointment","sun":"Closed"},
    "service_areas": ["Newcastle","Hunter Region"],
    "founded": "2020",
    "team_size": "20-50",
    "languages": ["English"],
    "features": ["NDIS Registered","SIL Provider","Plan Coordination"],
    "slug": "vhcc",
    "services": ["daily-living","personal-care","supported-living"],
    "location": "Newcastle",
    "category": "Daily Living",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#16a34a"
  },
  {
    "name": "Subee Support Services",
    "email": "info@subee.com.au",
    "tier": "professional",
    "verified": true,
    "categories": ["respite","cleaning","daily-living"],
    "suburb": "Newcastle",
    "state": "NSW",
    "postcode": "2300",
    "phone": "02 4088 8000",
    "website": "https://subee.com.au",
    "description": "Subee is an approved NDIS, Support at Home Program and iCare provider. Providing respite care for families and carers, plus NDIS cleaning and daily living services in Newcastle.",
    "short_description": "NDIS and iCare approved — respite care, cleaning and daily living support in Newcastle.",
    "rating": 4.3,
    "review_count": 8,
    "response_rate": 88,
    "response_time": "Within 24 hours",
    "wait_time": "1 week",
    "plan_types": ["NDIA Managed","Plan Managed","Self Managed"],
    "availability": {"mon":"7am-6pm","tue":"7am-6pm","wed":"7am-6pm","thu":"7am-6pm","fri":"7am-6pm","sat":"8am-2pm","sun":"Closed"},
    "service_areas": ["Newcastle","Coffs Harbour"],
    "founded": "2017",
    "team_size": "20-50",
    "languages": ["English"],
    "features": ["NDIS Registered","iCare Approved","Respite Specialists"],
    "slug": "subee-support-services",
    "services": ["respite","cleaning","daily-living"],
    "location": "Newcastle",
    "category": "Respite",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#d946ef"
  },
  {
    "name": "Oracle Psychology",
    "email": "admin@oraclepsychology.com.au",
    "tier": "professional",
    "verified": true,
    "categories": ["therapeutic","behaviour-support","psychology"],
    "suburb": "Newcastle",
    "state": "NSW",
    "postcode": "2300",
    "phone": "02 4929 3288",
    "website": "https://oraclepsychology.com.au",
    "description": "Oracle Psychology provides psychological assessments and therapeutic services for children, teens and adults. NDIS registered provider specialising in behaviour support and clinical psychology in Newcastle.",
    "short_description": "Child & adolescent psychology — behaviour support and therapeutic services in Newcastle.",
    "rating": 4.8,
    "review_count": 22,
    "response_rate": 96,
    "response_time": "1-2 business days",
    "wait_time": "3-4 weeks",
    "plan_types": ["NDIA Managed","Plan Managed","Self Managed"],
    "availability": {"mon":"9am-5pm","tue":"9am-5pm","wed":"9am-5pm","thu":"9am-5pm","fri":"9am-5pm","sat":"Closed","sun":"Closed"},
    "service_areas": ["Newcastle","Lake Macquarie"],
    "founded": "2012",
    "team_size": "10-20",
    "languages": ["English"],
    "features": ["NDIS Registered","Behaviour Support","Child Specialists"],
    "slug": "oracle-psychology",
    "services": ["therapeutic","behaviour-support","psychology"],
    "location": "Newcastle",
    "category": "Therapeutic",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#4f46e5"
  },
  {
    "name": "Loyal Support Services",
    "email": "info@loyalsupportservices.com.au",
    "tier": "professional",
    "verified": true,
    "categories": ["daily-living","community-access","transport"],
    "suburb": "Newcastle",
    "state": "NSW",
    "postcode": "2300",
    "phone": "1300 569 258",
    "website": "https://loyalsupportservices.com.au",
    "description": "Loyal Support Services is a reputable registered NDIS provider supporting NDIS participants and families across Sydney, Newcastle and NSW. Offering daily living, community access and transport assistance.",
    "short_description": "Reputable NDIS provider across Newcastle and Sydney — daily living, community access and transport.",
    "rating": 4.4,
    "review_count": 11,
    "response_rate": 90,
    "response_time": "Within 24 hours",
    "wait_time": "1-2 weeks",
    "plan_types": ["NDIA Managed","Plan Managed","Self Managed"],
    "availability": {"mon":"8am-6pm","tue":"8am-6pm","wed":"8am-6pm","thu":"8am-6pm","fri":"8am-6pm","sat":"By appointment","sun":"Closed"},
    "service_areas": ["Newcastle","Sydney","NSW Wide"],
    "founded": "2018",
    "team_size": "50-100",
    "languages": ["English","Arabic","Hindi"],
    "features": ["NDIS Registered","Transport Available","Multilingual"],
    "slug": "loyal-support-services",
    "services": ["daily-living","community-access","transport"],
    "location": "Newcastle",
    "category": "Daily Living",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#0284c7"
  },
  {
    "name": "Maple Community Services",
    "email": "hello@maplecommunity.com.au",
    "tier": "professional",
    "verified": true,
    "categories": ["coordination","supported-living","daily-living"],
    "suburb": "Newcastle",
    "state": "NSW",
    "postcode": "2300",
    "phone": "1300 627 538",
    "website": "https://maplecommunity.com.au",
    "description": "Maple Community Services is a trusted NDIS Support Coordinator connecting participants with the right supports. Helps match to a home and support model that fits goals, routines and preferences.",
    "short_description": "Trusted NDIS support coordination — connecting you with the right supports for your goals.",
    "rating": 4.5,
    "review_count": 15,
    "response_rate": 93,
    "response_time": "Within 24 hours",
    "wait_time": "1 week",
    "plan_types": ["NDIA Managed","Plan Managed","Self Managed"],
    "availability": {"mon":"8:30am-5pm","tue":"8:30am-5pm","wed":"8:30am-5pm","thu":"8:30am-5pm","fri":"8:30am-5pm","sat":"Closed","sun":"Closed"},
    "service_areas": ["Newcastle","Hunter Region","NSW Wide"],
    "founded": "2017",
    "team_size": "100+",
    "languages": ["English"],
    "features": ["NDIS Registered","Support Coordination","SIL Matching"],
    "slug": "maple-community-services",
    "services": ["coordination","supported-living","daily-living"],
    "location": "Newcastle",
    "category": "Support Coordination",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#15803d"
  },
  {
    "name": "Kuremara",
    "email": "info@kuremara.com.au",
    "tier": "professional",
    "verified": true,
    "categories": ["daily-living","community-access","supported-living"],
    "suburb": "Newcastle",
    "state": "NSW",
    "postcode": "2300",
    "phone": "1300 587 362",
    "website": "https://kuremara.com.au",
    "description": "Kuremara is a trusted registered NDIS provider across Australia offering reliable, inclusive disability support services tailored to individual needs.",
    "short_description": "Inclusive disability support services tailored to your needs — daily living and community access.",
    "rating": 4.2,
    "review_count": 6,
    "response_rate": 85,
    "response_time": "1-2 business days",
    "wait_time": "1-2 weeks",
    "plan_types": ["NDIA Managed","Plan Managed","Self Managed"],
    "availability": {"mon":"8am-5pm","tue":"8am-5pm","wed":"8am-5pm","thu":"8am-5pm","fri":"8am-5pm","sat":"Closed","sun":"Closed"},
    "service_areas": ["Newcastle","Australia Wide"],
    "founded": "2019",
    "team_size": "20-50",
    "languages": ["English","Aboriginal Languages"],
    "features": ["NDIS Registered","Culturally Safe","Indigenous Focus"],
    "slug": "kuremara",
    "services": ["daily-living","community-access","supported-living"],
    "location": "Newcastle",
    "category": "Daily Living",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#b45309"
  },
  {
    "name": "Help at Hand Support",
    "email": "info@helpathandsupport.com.au",
    "tier": "professional",
    "verified": true,
    "categories": ["daily-living","personal-care","community-access"],
    "suburb": "Newcastle",
    "state": "NSW",
    "postcode": "2300",
    "phone": "1300 435 726",
    "website": "https://helpathandsupport.com.au",
    "description": "Help at Hand Support is an NDIS-registered provider dedicated to enhancing independence and well-being through daily living, personal care and community access services across NSW.",
    "short_description": "Dedicated to enhancing independence — daily living, personal care and community access across NSW.",
    "rating": 4.3,
    "review_count": 7,
    "response_rate": 87,
    "response_time": "Within 24 hours",
    "wait_time": "1-2 weeks",
    "plan_types": ["NDIA Managed","Plan Managed","Self Managed"],
    "availability": {"mon":"7am-7pm","tue":"7am-7pm","wed":"7am-7pm","thu":"7am-7pm","fri":"7am-7pm","sat":"8am-4pm","sun":"Closed"},
    "service_areas": ["Newcastle","NSW Wide"],
    "founded": "2020",
    "team_size": "20-50",
    "languages": ["English"],
    "features": ["NDIS Registered","Flexible Hours","Weekend Available"],
    "slug": "help-at-hand-support",
    "services": ["daily-living","personal-care","community-access"],
    "location": "Newcastle",
    "category": "Daily Living",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#e11d48"
  },
  {
    "name": "Innerworks Disability Services",
    "email": "info@innerworksdisabilityservices.com.au",
    "tier": "professional",
    "verified": true,
    "categories": ["supported-living","mental-health","nursing"],
    "suburb": "Newcastle",
    "state": "NSW",
    "postcode": "2300",
    "phone": "02 4088 7000",
    "website": "https://innerworksdisabilityservices.com.au",
    "description": "Innerworks provides high-quality Supported Independent Living (SIL) for adults with severe psychosocial, intellectual and physical challenges. Team led by registered nurses with experience in critical NDIS disability care.",
    "short_description": "Specialist SIL provider — nurse-led care for complex psychosocial and physical disabilities.",
    "rating": 4.6,
    "review_count": 10,
    "response_rate": 91,
    "response_time": "Within 24 hours",
    "wait_time": "2-4 weeks",
    "plan_types": ["NDIA Managed","Plan Managed"],
    "availability": {"mon":"24/7","tue":"24/7","wed":"24/7","thu":"24/7","fri":"24/7","sat":"24/7","sun":"24/7"},
    "service_areas": ["Newcastle","Central Coast","Hunter Region"],
    "founded": "2018",
    "team_size": "50-100",
    "languages": ["English"],
    "features": ["NDIS Registered","24/7 Care","Nurse-Led","SIL Specialist"],
    "slug": "innerworks-disability-services",
    "services": ["supported-living","mental-health","nursing"],
    "location": "Newcastle",
    "category": "Supported Living",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#6d28d9"
  },
  {
    "name": "Ability Options",
    "email": "info@abilityoptions.org.au",
    "tier": "professional",
    "verified": true,
    "categories": ["employment","daily-living","community-access"],
    "suburb": "Newcastle",
    "state": "NSW",
    "postcode": "2300",
    "phone": "1800 801 900",
    "website": "https://www.abilityoptions.org.au",
    "description": "Ability Options is a leading disability employment and support provider helping people with disability find meaningful work and live independently across NSW including Newcastle.",
    "short_description": "Leading disability employment provider — helping people find meaningful work and independence.",
    "rating": 4.4,
    "review_count": 20,
    "response_rate": 92,
    "response_time": "Within 24 hours",
    "wait_time": "1-2 weeks",
    "plan_types": ["NDIA Managed","Plan Managed","Self Managed"],
    "availability": {"mon":"8:30am-5pm","tue":"8:30am-5pm","wed":"8:30am-5pm","thu":"8:30am-5pm","fri":"8:30am-5pm","sat":"Closed","sun":"Closed"},
    "service_areas": ["Newcastle","Sydney","NSW Wide"],
    "founded": "1976",
    "team_size": "500+",
    "languages": ["English","Mandarin","Arabic","Vietnamese"],
    "features": ["NDIS Registered","Employment Specialists","DES Provider"],
    "slug": "ability-options",
    "services": ["employment","daily-living","community-access"],
    "location": "Newcastle",
    "category": "Employment",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#0369a1"
  },
  {
    "name": "Cerebral Palsy Alliance",
    "email": "newcastle@cerebralpalsy.org.au",
    "tier": "professional",
    "verified": true,
    "categories": ["therapeutic","early-intervention","allied-health"],
    "suburb": "Lambton",
    "state": "NSW",
    "postcode": "2299",
    "phone": "1300 888 378",
    "website": "https://www.cerebralpalsy.org.au",
    "description": "Cerebral Palsy Alliance provides therapy, equipment and support for people with cerebral palsy and similar disabilities. Newcastle centre offers physiotherapy, OT, speech therapy and early intervention.",
    "short_description": "Specialist therapy and early intervention for cerebral palsy and similar disabilities.",
    "rating": 4.7,
    "review_count": 25,
    "response_rate": 95,
    "response_time": "Within 48 hours",
    "wait_time": "3-6 weeks",
    "plan_types": ["NDIA Managed","Plan Managed","Self Managed"],
    "availability": {"mon":"8am-5pm","tue":"8am-5pm","wed":"8am-5pm","thu":"8am-5pm","fri":"8am-5pm","sat":"Closed","sun":"Closed"},
    "service_areas": ["Newcastle","Lake Macquarie","Hunter Region"],
    "founded": "1945",
    "team_size": "200+",
    "languages": ["English"],
    "features": ["NDIS Registered","Allied Health","Early Intervention","Equipment"],
    "slug": "cerebral-palsy-alliance",
    "services": ["therapeutic","early-intervention","allied-health"],
    "location": "Lambton",
    "category": "Therapeutic",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#be123c"
  },
  {
    "name": "Northcott",
    "email": "newcastle@northcott.com.au",
    "tier": "professional",
    "verified": true,
    "categories": ["daily-living","supported-living","employment"],
    "suburb": "Newcastle",
    "state": "NSW",
    "postcode": "2300",
    "phone": "1800 818 286",
    "website": "https://www.northcott.com.au",
    "description": "Northcott is one of Australias largest disability service providers, supporting thousands of people with disability, their families and carers across NSW and ACT. Full range of NDIS services available in Newcastle.",
    "short_description": "One of Australias largest disability providers — full NDIS services in Newcastle.",
    "rating": 4.3,
    "review_count": 30,
    "response_rate": 90,
    "response_time": "Within 24 hours",
    "wait_time": "1-3 weeks",
    "plan_types": ["NDIA Managed","Plan Managed","Self Managed"],
    "availability": {"mon":"8am-5pm","tue":"8am-5pm","wed":"8am-5pm","thu":"8am-5pm","fri":"8am-5pm","sat":"Closed","sun":"Closed"},
    "service_areas": ["Newcastle","NSW Wide","ACT"],
    "founded": "1929",
    "team_size": "1000+",
    "languages": ["English","Auslan","Arabic","Mandarin"],
    "features": ["NDIS Registered","SIL Provider","Employment","Auslan"],
    "slug": "northcott",
    "services": ["daily-living","supported-living","employment"],
    "location": "Newcastle",
    "category": "Daily Living",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#4338ca"
  },
  {
    "name": "Everyday Independence",
    "email": "newcastle@everdayindependence.com.au",
    "tier": "professional",
    "verified": true,
    "categories": ["therapeutic","occupational-therapy","physiotherapy"],
    "suburb": "Newcastle",
    "state": "NSW",
    "postcode": "2300",
    "phone": "1300 179 131",
    "website": "https://www.everydayindependence.com.au",
    "description": "Everyday Independence provides allied health therapy in the community — occupational therapy, physiotherapy, speech pathology and behaviour support. We come to you at home, school or in the community.",
    "short_description": "Allied health therapy that comes to you — OT, physio, speech and behaviour support.",
    "rating": 4.5,
    "review_count": 16,
    "response_rate": 93,
    "response_time": "1-2 business days",
    "wait_time": "2-4 weeks",
    "plan_types": ["NDIA Managed","Plan Managed","Self Managed"],
    "availability": {"mon":"8am-6pm","tue":"8am-6pm","wed":"8am-6pm","thu":"8am-6pm","fri":"8am-6pm","sat":"Closed","sun":"Closed"},
    "service_areas": ["Newcastle","Lake Macquarie","Maitland","Hunter Valley"],
    "founded": "2017",
    "team_size": "200+",
    "languages": ["English"],
    "features": ["NDIS Registered","Mobile Service","Allied Health","Home Visits"],
    "slug": "everyday-independence",
    "services": ["therapeutic","occupational-therapy","physiotherapy"],
    "location": "Newcastle",
    "category": "Therapeutic",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#0891b2"
  },
  {
    "name": "Uniting",
    "email": "newcastle@uniting.org",
    "tier": "professional",
    "verified": true,
    "categories": ["daily-living","community-access","early-intervention"],
    "suburb": "Maitland",
    "state": "NSW",
    "postcode": "2320",
    "phone": "1800 864 846",
    "website": "https://www.uniting.org",
    "description": "Uniting is one of the largest providers of community services in NSW and ACT. As an NDIS Local Area Coordinator partner in the Hunter, Uniting connects participants with supports and helps manage plans.",
    "short_description": "Major NDIS Local Area Coordinator partner — connecting Hunter participants with the right supports.",
    "rating": 4.1,
    "review_count": 12,
    "response_rate": 85,
    "response_time": "1-3 business days",
    "wait_time": "2-3 weeks",
    "plan_types": ["NDIA Managed","Plan Managed"],
    "availability": {"mon":"9am-5pm","tue":"9am-5pm","wed":"9am-5pm","thu":"9am-5pm","fri":"9am-5pm","sat":"Closed","sun":"Closed"},
    "service_areas": ["Maitland","Newcastle","Hunter Region"],
    "founded": "1977",
    "team_size": "500+",
    "languages": ["English"],
    "features": ["NDIS Registered","LAC Partner","Early Intervention"],
    "slug": "uniting",
    "services": ["daily-living","community-access","early-intervention"],
    "location": "Maitland",
    "category": "Daily Living",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#1d4ed8"
  },
  {
    "name": "Allowah Presbyterian Childrens Hospital",
    "email": "admin@allowah.org.au",
    "tier": "professional",
    "verified": true,
    "categories": ["respite","paediatric","nursing"],
    "suburb": "Dundas",
    "state": "NSW",
    "postcode": "2117",
    "phone": "02 9684 3600",
    "website": "https://www.allowah.org.au",
    "description": "Specialist paediatric respite and nursing care for children with complex disabilities. NDIS registered for short-term accommodation and respite services in the Hunter and Sydney regions.",
    "short_description": "Specialist paediatric respite and nursing care for children with complex disabilities.",
    "rating": 4.9,
    "review_count": 8,
    "response_rate": 90,
    "response_time": "1-2 business days",
    "wait_time": "4-8 weeks",
    "plan_types": ["NDIA Managed","Plan Managed"],
    "availability": {"mon":"24/7","tue":"24/7","wed":"24/7","thu":"24/7","fri":"24/7","sat":"24/7","sun":"24/7"},
    "service_areas": ["Hunter Region","Sydney","NSW Wide"],
    "founded": "1920",
    "team_size": "50+",
    "languages": ["English"],
    "features": ["NDIS Registered","24/7 Nursing","Paediatric Specialist"],
    "slug": "allowah-childrens-hospital",
    "services": ["respite","paediatric","nursing"],
    "location": "Dundas",
    "category": "Respite",
    "plan": "free",
    "registration_ready": true,
    "brand_color": "#db2777"
  }
]
'@

Set-Content -Path "$env:TEMP\providers.json" -Value $providers -Encoding UTF8 -NoNewline

$result = curl.exe -s -X POST $url -H "apikey: $svc" -H "Authorization: Bearer $svc" -H "Content-Type: application/json" -H "Prefer: return=representation" -d "@$env:TEMP\providers.json" 2>&1

# Count inserted
$parsed = $result | ConvertFrom-Json -ErrorAction SilentlyContinue
if ($parsed) { Write-Output "Inserted $($parsed.Count) providers" }
else { Write-Output "Result: $($result.Substring(0, [Math]::Min(500, $result.Length)))" }
