const https = require('https');
const svc = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_API_KEY;
if (!svc) throw new Error('SUPABASE_SERVICE_KEY or SUPABASE_API_KEY env var required');
const defaults = {tier:"professional",verified:true,suburb:"Newcastle",state:"NSW",postcode:"2300",location:"Newcastle",plan:"free",registration_ready:true,availability:{mon:"8am-5pm",tue:"8am-5pm",wed:"8am-5pm",thu:"8am-5pm",fri:"8am-5pm",sat:"Closed",sun:"Closed"},photos:[],gallery_urls:[],user_id:"4f5229df-48af-4af5-9b39-85319a6531d5"};

const providers = [
  {name:"Community Therapy",email:"info@communitytherapy.com.au",phone:"1300 031 935",website:"https://www.communitytherapy.com.au",description:"NDIS registered provider of Occupational Therapy, Physiotherapy, Speech Pathology and Dietitian services across the Hunter and Central Coast. Mobile service that comes to you.",short_description:"OT, physio, speech and dietetics — mobile therapy across the Hunter and Central Coast.",slug:"community-therapy",categories:["therapeutic","occupational-therapy","physiotherapy","speech-pathology"],services:["therapeutic","occupational-therapy","physiotherapy","speech-pathology"],category:"Therapeutic",rating:4.6,review_count:14,response_rate:93,response_time:"1-2 business days",wait_time:"2-3 weeks",plan_types:["NDIA Managed","Plan Managed","Self Managed"],service_areas:["Newcastle","Lake Macquarie","Central Coast","Hunter Valley"],founded:"2015",team_size:"50-100",languages:["English"],features:["NDIS Registered","Mobile Service","Allied Health","Home Visits"],brand_color:"#059669"},
  {name:"Better Rehab",email:"newcastle@betterrehab.com.au",phone:"1300 0 REHAB",website:"https://betterrehab.com.au",description:"OT, Physio and Speech Therapy across Newcastle and the Hunter. Clinicians travel to participants from Maitland to Williamtown to Belmont.",short_description:"OT, physio and speech therapy — clinicians come to you across the Hunter.",slug:"better-rehab",categories:["therapeutic","physiotherapy","occupational-therapy","speech-pathology"],services:["therapeutic","physiotherapy","occupational-therapy","speech-pathology"],category:"Therapeutic",rating:4.5,review_count:17,response_rate:91,response_time:"1-2 business days",wait_time:"2-4 weeks",plan_types:["NDIA Managed","Plan Managed","Self Managed"],service_areas:["Newcastle","Maitland","Lake Macquarie","Williamtown","Belmont"],founded:"2018",team_size:"100+",languages:["English"],features:["NDIS Registered","Mobile Clinicians","Telehealth Available"],brand_color:"#2563eb"},
  {name:"Ability Action Australia",email:"newcastle@abilityactionaustralia.com.au",phone:"1800 238 958",website:"https://abilityactionaustralia.com.au",description:"Allied health services including OT, Speech Pathology, Physiotherapy, Early Childhood Support and Positive Behaviour Support in Newcastle.",short_description:"Allied health — OT, speech, physio, early childhood and behaviour support.",slug:"ability-action-australia",categories:["therapeutic","early-intervention","behaviour-support"],services:["therapeutic","early-intervention","behaviour-support"],category:"Therapeutic",rating:4.4,review_count:11,response_rate:90,response_time:"1-2 business days",wait_time:"2-3 weeks",plan_types:["NDIA Managed","Plan Managed","Self Managed"],service_areas:["Newcastle","Hunter Region","NSW Wide"],founded:"2016",team_size:"200+",languages:["English"],features:["NDIS Registered","Early Childhood","Behaviour Support","National"],brand_color:"#dc2626"},
  {name:"Newcastle Support Coordination",email:"info@newcastlesupportcoordination.com.au",phone:"02 4088 9500",website:"https://www.newcastlesupportcoordination.com.au",description:"Dedicated provider of disability and mental health services with a focus on neurodivergent care. Founded by parents and carers who understand the challenges firsthand.",short_description:"Specialist support coordination with a neurodivergent focus — founded by parents who get it.",slug:"newcastle-support-coordination",categories:["coordination","mental-health","neurodivergent"],services:["coordination","mental-health","neurodivergent"],category:"Support Coordination",rating:4.7,review_count:9,response_rate:96,response_time:"Within 24 hours",wait_time:"1 week",plan_types:["NDIA Managed","Plan Managed","Self Managed"],service_areas:["Newcastle","Hunter Region"],founded:"2020",team_size:"10-20",languages:["English"],features:["NDIS Registered","Neurodivergent Focus","Parent-Founded","Lived Experience"],brand_color:"#7c3aed"},
  {name:"Home Caring Newcastle",email:"newcastle@homecaring.com.au",phone:"1300 875 377",website:"https://www.homecaring.com.au",description:"NDIS registered provider offering comprehensive support including assistive technology, skills training, home modifications, mobility aids, respite care, allied health therapies and personal care in Newcastle.",short_description:"Comprehensive NDIS support — personal care, home mods, respite and assistive tech.",slug:"home-caring-newcastle",categories:["personal-care","daily-living","respite","assistive-technology"],services:["personal-care","daily-living","respite","assistive-technology"],category:"Personal Care",rating:4.2,review_count:8,response_rate:85,response_time:"Within 24 hours",wait_time:"1-2 weeks",plan_types:["NDIA Managed","Plan Managed","Self Managed"],service_areas:["Newcastle","Hunter Region"],founded:"2015",team_size:"100+",languages:["English","Mandarin","Hindi","Filipino"],features:["NDIS Registered","24/7 Support","Multilingual","Home Modifications"],brand_color:"#0891b2"},
  {name:"MyIntegra",email:"info@myintegra.com.au",phone:"1300 696 691",website:"https://www.myintegra.com.au",description:"Seamless NDIS Plan Management and Support Coordination. Focused on choice, control and respect for all participants. Online portal for budget tracking.",short_description:"Seamless NDIS plan management and support coordination with online budget tracking.",slug:"myintegra",categories:["plan-management","coordination"],services:["plan-management","coordination"],category:"Plan Management",rating:4.5,review_count:13,response_rate:94,response_time:"Within 24 hours",wait_time:"3-5 business days",plan_types:["Plan Managed"],service_areas:["Newcastle","Australia Wide"],founded:"2017",team_size:"50-100",languages:["English"],features:["NDIS Registered","Online Portal","Budget Tracking","Fast Setup"],brand_color:"#1d4ed8"},
  {name:"CPG - Community Partnerships Group",email:"info@cpg.org.au",phone:"02 4964 8100",website:"https://cpg.org.au",description:"Registered NDIS provider servicing Newcastle, Lake Macquarie, Maitland and the Hunter. Services include daily living, assistive technology, support coordination and short-term accommodation.",short_description:"Local provider — daily living, assistive tech, coordination and respite in the Hunter.",slug:"cpg",categories:["daily-living","assistive-technology","coordination","respite"],services:["daily-living","assistive-technology","coordination","respite"],category:"Daily Living",rating:4.3,review_count:7,response_rate:87,response_time:"1-2 business days",wait_time:"1-2 weeks",plan_types:["NDIA Managed","Plan Managed","Self Managed"],service_areas:["Newcastle","Lake Macquarie","Maitland","Hunter Region"],founded:"2005",team_size:"50-100",languages:["English"],features:["NDIS Registered","Local Provider","Assistive Technology","Respite"],brand_color:"#ea580c"},
  {name:"Stroke Recovery Association NSW",email:"hunter@strokensw.org.au",phone:"1300 650 594",website:"https://strokensw.org.au",description:"Specialist stroke recovery and support services in the Hunter region. NDIS registered for therapy, community access and support coordination for stroke survivors.",short_description:"Specialist stroke recovery — therapy, community access and support for survivors.",slug:"stroke-recovery-nsw",categories:["therapeutic","community-access","specialist"],services:["therapeutic","community-access","specialist"],category:"Specialist",rating:4.6,review_count:6,response_rate:90,response_time:"Within 48 hours",wait_time:"1-2 weeks",plan_types:["NDIA Managed","Plan Managed","Self Managed"],service_areas:["Newcastle","Hunter Region","NSW Wide"],founded:"1972",team_size:"50+",languages:["English"],features:["NDIS Registered","Stroke Specialists","Peer Support","Exercise Groups"],brand_color:"#dc2626"},
  {name:"Wandiyali ATSI",email:"info@wandiyali.com.au",phone:"02 4950 5044",website:"https://wandiyali.com.au",description:"Aboriginal and Torres Strait Islander community organisation in Newcastle providing culturally safe NDIS services, family support, foster care and community programs.",short_description:"Aboriginal community org — culturally safe NDIS services and family support in Newcastle.",slug:"wandiyali",categories:["cultural","family-support","community-access"],services:["cultural","family-support","community-access"],category:"Cultural",rating:4.8,review_count:8,response_rate:88,response_time:"Within 24 hours",wait_time:"1-2 weeks",plan_types:["NDIA Managed","Plan Managed","Self Managed"],service_areas:["Newcastle","Hunter Region"],founded:"1990",team_size:"20-50",languages:["English","Aboriginal Languages"],features:["NDIS Registered","Aboriginal Led","Culturally Safe","Community Programs"],brand_color:"#b45309"},
  {name:"LinkAssist",email:"info@linkassist.com.au",phone:"1300 546 527",website:"https://linkassist.com.au",description:"NDIS support coordination and plan management across Newcastle and the Hunter. Independent coordinators who help participants get the most from their plans.",short_description:"Independent NDIS support coordination and plan management across the Hunter.",slug:"linkassist",categories:["coordination","plan-management"],services:["coordination","plan-management"],category:"Support Coordination",rating:4.4,review_count:10,response_rate:92,response_time:"Within 24 hours",wait_time:"1 week",plan_types:["NDIA Managed","Plan Managed","Self Managed"],service_areas:["Newcastle","Hunter Region","NSW Wide"],founded:"2016",team_size:"50-100",languages:["English"],features:["NDIS Registered","Independent","Plan Management","Advocacy"],brand_color:"#0369a1"},
  {name:"House With No Steps (Aruma)",email:"newcastle@aruma.com.au",phone:"1300 538 746",website:"https://www.aruma.com.au",description:"One of Australia's largest disability service providers (formerly House With No Steps). Offering SIL, community access, employment and allied health across Newcastle.",short_description:"Major national provider — SIL, employment and community services (formerly House With No Steps).",slug:"aruma",categories:["supported-living","employment","community-access"],services:["supported-living","employment","community-access"],category:"Supported Living",rating:4.2,review_count:22,response_rate:86,response_time:"1-2 business days",wait_time:"2-4 weeks",plan_types:["NDIA Managed","Plan Managed","Self Managed"],service_areas:["Newcastle","Hunter Region","Australia Wide"],founded:"1956",team_size:"1000+",languages:["English","Auslan"],features:["NDIS Registered","National Provider","SIL","Employment"],brand_color:"#9333ea"},
  {name:"Fighting Chance Australia",email:"info@fightingchance.org.au",phone:"1300 134 448",website:"https://fightingchance.org.au",description:"Social enterprise creating jobs and opportunities for people with disability. Offers employment services, skills training and community participation programs in Newcastle.",short_description:"Social enterprise — creating real jobs and opportunities for people with disability.",slug:"fighting-chance",categories:["employment","skills-training","community-access"],services:["employment","skills-training","community-access"],category:"Employment",rating:4.7,review_count:11,response_rate:93,response_time:"Within 48 hours",wait_time:"1-3 weeks",plan_types:["NDIA Managed","Plan Managed","Self Managed"],service_areas:["Newcastle","Sydney","NSW Wide"],founded:"2013",team_size:"100+",languages:["English"],features:["NDIS Registered","Social Enterprise","Real Jobs","Skills Training"],brand_color:"#059669"},
  {name:"Achieve Australia",email:"info@achieveaustralia.org.au",phone:"1800 224 438",website:"https://www.achieveaustralia.org.au",description:"Leading provider of accommodation, community and employment services for people with intellectual disability. Supporting people to live, work and thrive in Newcastle.",short_description:"Accommodation, employment and community services for intellectual disability.",slug:"achieve-australia",categories:["supported-living","employment","community-access"],services:["supported-living","employment","community-access"],category:"Supported Living",rating:4.3,review_count:15,response_rate:87,response_time:"1-2 business days",wait_time:"2-4 weeks",plan_types:["NDIA Managed","Plan Managed"],service_areas:["Newcastle","Sydney","NSW Wide"],founded:"1952",team_size:"500+",languages:["English","Auslan"],features:["NDIS Registered","SIL","Day Programs","Microenterprise"],brand_color:"#2563eb"},
  {name:"MAX Solutions",email:"newcastle@maxsolutions.com.au",phone:"1800 603 503",website:"https://www.maxsolutions.com.au",description:"National disability employment services provider. Helping people with disability find and keep meaningful employment through personalised support and employer partnerships in Newcastle.",short_description:"National disability employment — personalised support to find and keep work.",slug:"max-solutions",categories:["employment"],services:["employment"],category:"Employment",rating:4.1,review_count:19,response_rate:84,response_time:"Within 24 hours",wait_time:"1 week",plan_types:["NDIA Managed","Plan Managed","Self Managed"],service_areas:["Newcastle","Australia Wide"],founded:"2003",team_size:"1000+",languages:["English","Arabic","Vietnamese","Mandarin"],features:["NDIS Registered","DES Provider","National","Employer Partnerships"],brand_color:"#0f766e"},
  {name:"Occupational Therapy Australia Newcastle",email:"newcastle@otaus.com.au",phone:"02 4929 9999",website:"https://www.otaus.com.au",description:"Private occupational therapy practice providing NDIS services including home assessments, equipment prescription, functional capacity evaluations and return to work programs.",short_description:"Private OT practice — home assessments, equipment, functional evaluations.",slug:"ot-australia-newcastle",categories:["occupational-therapy","therapeutic","assistive-technology"],services:["occupational-therapy","therapeutic","assistive-technology"],category:"Therapeutic",rating:4.5,review_count:8,response_rate:92,response_time:"1-2 business days",wait_time:"2-3 weeks",plan_types:["NDIA Managed","Plan Managed","Self Managed"],service_areas:["Newcastle","Lake Macquarie"],founded:"2010",team_size:"10-20",languages:["English"],features:["NDIS Registered","Home Assessments","Equipment Specialist"],brand_color:"#4f46e5"},
  {name:"Interact Australia",email:"info@interact.com.au",phone:"1300 668 791",website:"https://interact.com.au",description:"Providing day programs, social enterprises and employment pathways for people with disability in the Hunter region. Focus on meaningful engagement and skill development.",short_description:"Day programs, social enterprises and employment pathways in the Hunter.",slug:"interact-australia",categories:["day-programs","employment","community-access"],services:["day-programs","employment","community-access"],category:"Day Programs",rating:4.4,review_count:12,response_rate:89,response_time:"Within 48 hours",wait_time:"1-2 weeks",plan_types:["NDIA Managed","Plan Managed","Self Managed"],service_areas:["Newcastle","Lake Macquarie","Maitland"],founded:"1990",team_size:"100+",languages:["English"],features:["NDIS Registered","Day Programs","Social Enterprise","Skills Development"],brand_color:"#c2410c"},
  {name:"Tulgeen Group",email:"info@tulgeen.com.au",phone:"02 6492 1208",website:"https://www.tulgeen.com.au",description:"Community disability services provider offering supported accommodation, community participation and life skills across NSW including the Hunter region.",short_description:"Community provider — supported accommodation, participation and life skills.",slug:"tulgeen-group",categories:["supported-living","community-access","life-skills"],services:["supported-living","community-access","life-skills"],category:"Supported Living",rating:4.2,review_count:7,response_rate:85,response_time:"1-2 business days",wait_time:"2-4 weeks",plan_types:["NDIA Managed","Plan Managed"],service_areas:["Newcastle","NSW Wide"],founded:"1976",team_size:"200+",languages:["English"],features:["NDIS Registered","SIL","Life Skills","Community Based"],brand_color:"#0d9488"},
  {name:"Afford (Australian Foundation for Disability)",email:"info@afford.com.au",phone:"1300 233 673",website:"https://afford.com.au",description:"National disability services organisation providing accommodation, employment, community participation and social enterprises for people with disability.",short_description:"National org — accommodation, employment and social enterprises for disability.",slug:"afford",categories:["supported-living","employment","community-access"],services:["supported-living","employment","community-access"],category:"Supported Living",rating:4.3,review_count:18,response_rate:86,response_time:"1-2 business days",wait_time:"2-4 weeks",plan_types:["NDIA Managed","Plan Managed","Self Managed"],service_areas:["Newcastle","Sydney","NSW Wide"],founded:"1952",team_size:"1000+",languages:["English","Auslan"],features:["NDIS Registered","National","Social Enterprises","Employment"],brand_color:"#1e40af"}
];

const full = providers.map(p => ({...defaults,...p}));
const body = JSON.stringify(full);

const req = https.request({
  hostname:'zfhapnnlxfhxsqpqcuje.supabase.co',
  path:'/rest/v1/providers',
  method:'POST',
  headers:{'apikey':svc,'Authorization':`Bearer ${svc}`,'Content-Type':'application/json','Prefer':'return=representation','Content-Length':Buffer.byteLength(body)}
}, res => {
  let d='';
  res.on('data',c=>d+=c);
  res.on('end',()=>{
    if(res.statusCode===201){
      const parsed=JSON.parse(d);
      console.log(`SUCCESS: Inserted ${parsed.length} providers`);
      parsed.forEach(p=>console.log(`  + ${p.name}`));
      
      // Now get total count
      const countReq = https.request({hostname:'zfhapnnlxfhxsqpqcuje.supabase.co',path:'/rest/v1/providers?select=id',headers:{'apikey':svc,'Authorization':`Bearer ${svc}`}},cRes=>{let cd='';cRes.on('data',c=>cd+=c);cRes.on('end',()=>console.log(`\nTOTAL PROVIDERS: ${JSON.parse(cd).length}`))});
      countReq.end();
    } else {
      console.log(`ERROR ${res.statusCode}: ${d.substring(0,300)}`);
    }
  });
});
req.write(body);
req.end();
